In [20]:
import pandas as pd
df=pd.read_csv("south_india.csv")
df.sort_values("Departure Percentage: JUN-SEPT",ascending=False)['YEAR'].head(1)

82    1983
Name: YEAR, dtype: int64

In [21]:
df=pd.read_csv("ne-India_rainfall_act_dep_1901_2016.csv")
df.sort_values("Departure Percentage: JUN-SEPT",ascending=False)['YEAR'].head(1)

86    1987
Name: YEAR, dtype: int64

In [22]:
df=pd.read_csv("nw-India_rainfall_act_dep_1901_2016.csv")
df.sort_values("Departure Percentage: JUN-SEPT",ascending=False)['YEAR'].head(1)

16    1917
Name: YEAR, dtype: int64

In [23]:
df=pd.read_csv("central-India_rainfall_act_dep_1901_2016.csv")
df.sort_values("Departure Percentage: JUN-SEPT",ascending=False)['YEAR'].head(1)

60    1961
Name: YEAR, dtype: int64

In [26]:
file = 'METEOROLOGICAL_SUB_DIVISION_WISE_ANNUAL_RAINFALL.xls'
mfile = pd.read_excel(file)
mfile

,Sub-division,2002 (in millimetre),2003 (in millimetre),2004 (in millimetre),2005 (in millimetre),2006 (in millimetre),2007 (in millimetre),2008 (in millimetre),2009 (in millimetre),2010 (in millimetre),Normal Rainfall 2010 (in millimetre),Percentage change w.r.t Normal Rainfall in 2010,2011 (in millimetre),Normal Rainfall 2011 (in millimetre),Percentage change w.r.t Normal Rainfall in 2011
0,Andaman and Nicobar Islands,2310.7,2446.9,2508.1,2762.6,2447.9,2656.7,3335.2,2614.5,3147.2,2974.4,5.809575,3833.5,2926.3,31.001606
1,Arunachal Pradesh,2559.6,2761.2,2891.7,2542.4,2108.0,2401.3,2470.4,2163.3,2397.7,2783.3,-13.854058,1923.4,2933.7,-34.437741
2,Assam and Meghalaya,2530.4,2835.1,2890.9,2314.8,1777.4,2414.6,2271.2,1863.0,2498.7,2898.2,-13.784418,1758.3,2624.9,-33.014591
3,"Nagaland,Mizoram,Manipur and Tripura",1960.8,2029.0,1999.3,1612.4,1561.6,2146.0,1481.7,1446.5,2027.2,2139.5,-5.248890,1655.0,2278.0,-27.348551
4,"Sub-Himalayan,West Bengal & Sikkim",2820.1,3288.5,2768.3,2670.8,2304.5,2641.3,2618.8,2275.1,2849.3,2600.9,9.550540,2360.0,2708.9,-12.879767
5,Gangetic West Bengal,1597.5,1457.8,1488.1,1585.4,1587.3,1953.2,1580.6,1322.5,1084.4,1492.9,-27.362851,1671.7,1527.2,9.461760
6,Orissa,1166.6,1750.6,1337.6,1549.7,1810.0,1664.9,1600.4,1397.8,1332.3,1478.6,-9.894495,1300.2,1460.5,-10.975693
7,Jharkhand,1315.5,1299.0,1153.5,859.4,1356.0,1441.5,1200.6,1061.1,803.7,1306.6,-38.489209,1274.8,1296.3,-1.658567
8,Bihar,1193.3,1454.8,1077.0,913.7,1000.5,1466.2,1306.7,993.7,941.9,1213.6,-22.387937,1217.3,1205.6,0.970471
9,Uttar Pradesh East,796.0,1177.1,902.4,828.3,771.5,863.2,1121.9,711.1,758.5,1036.2,-26.799846,874.9,1018.6,-14.107599
10,Uttar Pradesh West,729.1,1129.5,647.2,752.6,510.4,586.1,840.4,552.4,818.7,885.5,-7.543761,776.0,886.2,-12.435116
11,Uttranchal,1588.5,1903.7,1584.4,1469.3,1264.8,1894.4,1298.5,1076.0,1864.3,1564.5,19.162672,1708.2,1580.9,8.052375
12,"Haryana,Chandigarh & Delhi",471.8,720.7,524.0,586.9,377.1,479.9,633.0,350.4,598.1,563.5,6.140195,433.0,562.8,-23.063255
13,Punjab,446.1,645.1,445.1,603.5,544.6,494.3,708.7,403.8,501.1,641.6,-21.898379,533.6,635.9,-16.087435
14,Himachal Pradesh,1075.5,1268.9,766.4,996.4,895.8,862.5,1048.9,805.7,1227.9,1323.7,-7.237289,1051.8,1373.9,-23.444210
15,Jammu & Kashmir,750.5,1106.1,916.1,1309.8,1477.3,1037.9,1087.2,872.6,1257.6,1234.3,1.887710,1122.1,1205.3,-6.902846
16,Rajasthan West,118.9,386.7,190.3,260.3,362.4,282.2,309.7,166.6,473.2,296.4,59.649123,426.7,299.2,42.613636
17,Rajasthan East,307.2,629.7,627.5,617.4,711.6,553.5,627.1,460.6,741.3,684.7,8.266394,849.1,671.3,26.485923
18,Madhya Pradesh West,754.7,1011.0,839.7,784.4,1140.6,887.8,747.7,797.2,817.9,987.6,-17.183070,1062.3,956.3,11.084388
19,Madhya Pradesh East,1075.7,1532.5,946.8,1408.4,1007.6,864.1,989.8,910.5,966.3,1220.4,-20.821042,1220.7,1169.4,4.386865
20,Gujarat Region,705.4,1259.4,1004.2,1385.4,1458.0,1158.8,932.5,649.4,1059.8,954.3,11.055224,903.9,943.4,-4.186983
21,"Saurashtra,Kutch & Diu",402.7,733.1,498.3,638.6,702.9,892.1,572.4,616.9,1073.9,519.2,106.837442,725.0,507.0,42.998028
22,Konkan & Goa,2324.2,2828.5,2911.7,3557.5,3378.9,3401.1,3051.6,2738.3,3749.4,2975.7,26.000605,3842.4,3100.2,23.940391
23,Madhya Maharashtra,711.7,740.3,883.4,1101.6,1180.8,921.5,858.8,918.1,1006.3,850.1,18.374309,842.9,876.8,-3.866332
24,Marathwada,704.8,645.2,676.5,864.3,819.3,625.6,651.1,687.5,1039.4,846.3,22.816968,685.7,821.6,-16.540896
25,Vidarbha,1045.4,1033.1,796.3,1257.7,1276.5,1135.8,855.7,804.2,1355.2,1103.3,22.831505,958.5,1084.5,-11.618257
26,Chattisgarh,NaN,1702.7,1174.3,1305.1,1231.5,1244.1,1144.0,859.7,1147.8,1363.3,-15.807232,1313.0,1290.7,1.727745
27,Coastal Andhra Pradesh,757.3,1118.6,933.7,1238.9,1067.1,1093.9,1057.1,745.0,1624.9,1011.3,60.674380,835.5,1024.4,-18.440062
28,Telangana,767.7,1006.7,761.7,1230.8,1044.6,902.6,998.0,665.8,1248.9,941.7,32.621854,739.6,942.6,-21.536177
29,Rayalseema,504.4,654.0,655.9,999.2,608.9,934.1,795.1,672.8,907.1,678.0,33.790560,642.8,706.1,-8.964736
30,Tamil Nadu,723.4,925.0,1104.6,1314.0,911.9,968.8,1195.7,934.4,1122.2,908.8,23.481514,1013.8,914.4,10.870516
31,Coastal Karnataka,2920.4,3086.5,3061.6,3274.8,3865.9,3904.7,3050.8,3798.2,4007.5,3613.2,10.912764,4146.4,3526.3,17.585004
32,North Interior Karnataka,556.3,473.6,644.5,856.1,628.0,788.5,700.5,977.1,857.3,720.4,19.003331,620.2,740.3,-16.223153
33,South Interior Karnataka,869.1,817.9,1028.3,1357.0,951.0,1229.5,1105.7,1177.2,1308.7,1029.5,27.119961,1040.5,1019.2,2.089874
34,Kerala,2457.3,2275.8,2911.3,3151.0,3297.7,3919.5,2534.2,2815.9,3142.0,3094.9,1.521859,3041.6,2924.3,4.011216
35,Lakshadweep,1034.4,1533.2,2096.8,1579.0,1695.4,2037.9,1726.4,1572.5,1725.4,1584.7,8.878652,1531.4,1600.0,-4.287500

In [36]:
mfile = pd.read_excel(file)

KeyError: 'Sub-division'

In [40]:
import matplotlib.pyplot as plt

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv('', index_col = False)


#plot data
plt.plot(data['Year'], data['Product 1'], linestyle="dotted", marker='^', color="red", label = 'Product 1')

plt.plot(data['Year'], data['Product 2'], linestyle="solid", marker='o', color="green", label = 'Product 2')

plt.plot(data['Year'], data['Product 3'], linestyle="dashed", marker='<', color="blue", label = 'Product 3')



#labels
plt.xlabel("Year")
plt.ylabel("Number in units")

# add legend
plt.legend()

#title
plt.title("Poduct Analysis")

# save plot as image
plt.savefig('products.jpg')